---
- hosts: "all"
  become: yes
  pre_tasks:
     - shell: python  /vagrant/setup.py install
  roles:
    - role: jimbydamonk.rabbitmq
      rabbitmq_vhosts:
        - name: collectd
        - name: vhost2
      rabbitmq_users:
        - vhost:    collectd
          name:     collectd
          password: collectd
          tags: administrator
        - vhost:    vhost2
          name:     collectd
          password: collectd
          tags: administrator
      rabbitmq_permissions:
        - user: collectd
          vhost: vhost2
          configure: ".*"
          write: ".*"
          read: ".*"
        - user: collectd
          vhost: collectd
          configure: ".*"
          write: ".*"
          read: ".*"
        - user: "collectd"
          vhost: "/"
          configure: ".*"
          write: ".*"
          read: ".*"
    - role: jimbydamonk.collectd
      collectd_plugins:
        - syslog
        - logfile

      collectd_plugins_config:
        logfile:
          LogLevel: "info"
          File: "/var/log/collectd.log"
          Timestamp: true
          PrintSeverity: false
        syslog:
          LogLevel: info

      collectd_template_files:
        - src: "{{ playbook_dir }}/templates/graphite.conf.j2"
        - src: "{{ playbook_dir }}/templates/rabbit.conf.j2"
    - role: jimbydamonk.graphite

  tasks:
    - name: Install pika
      pip:
        name: pika

    - name: Install requests for ansible to be able to create rabbit objects
      pip:
        name: requests

    - name: Flush role handlers
      meta: flush_handlers

    - name: Create test topic exchange
      rabbitmq_exchange:
        name: test_topic_exchange
        type: topic
        vhost: collectd
        login_user: collectd
        login_password: collectd

    - name: Create test queue
      rabbitmq_queue:
        name: test_queue
        vhost: collectd
        login_user: collectd
        login_password: collectd

    - name: Create test binding
      rabbitmq_binding:
        name: test_topic_exchange
        destination: test_queue
        type: queue
        routing_key: test
        vhost: collectd
        login_user: collectd
        login_password: collectd

    - name: Create test topic exchange for vhost2
      rabbitmq_exchange:
        name: test_topic_exchange2
        type: topic
        vhost: vhost2
        login_user: collectd
        login_password: collectd

    - name: Create test queue for vhost2
      rabbitmq_queue:
        name: test_queue2
        vhost: vhost2
        login_user: collectd
        login_password: collectd

    - name: Create test binding for vhost2
      rabbitmq_binding:
        name: test_topic_exchange2
        destination: test_queue2
        type: queue
        routing_key: test
        vhost: vhost2
        login_user: collectd
        login_password: collectd